CREATE TABLE IF NOT EXISTS vehicleshop_shops (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  coords JSON NOT NULL,
  spawn JSON NOT NULL,
  blip JSON DEFAULT NULL,
  data JSON NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;